apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  labels:
    app: coreos
    component: cert-manager
    environment: ${ENVIRONMENT}
    cluster: ${CLUSTER_NAME}
    managed-by: terraform
  annotations:
    # Retry configuration for certificate issuance
    cert-manager.io/retry-interval: "2h"
    cert-manager.io/max-retries: "5"
    # Monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "9402"
    monitoring.coreos.com/alert-threshold: "15d"
    # Backup configuration
    backup.velero.io/backup-volumes: "true"

spec:
  acme:
    # Production Let's Encrypt ACME server
    server: ${ACME_SERVER}
    email: ${ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: istio
            podTemplate:
              metadata:
                labels:
                  app: cert-solver
                  security-critical: "true"
              spec:
                # Security context for solver pods
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 1000
                # Resource limits and requests
                resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "200m"
                    memory: "256Mi"