apiVersion: external-secrets.io/v1beta1  # external-secrets.io v1beta1
kind: ExternalSecret
metadata:
  name: coreos-external-secret
  namespace: coreos
  labels:
    app.kubernetes.io/name: coreos
    app.kubernetes.io/part-of: coreos-platform
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: external-secrets
  annotations:
    kubernetes.io/description: Core platform secrets managed by External Secrets Operator
    external-secrets.io/refresh-interval: "1h"
    external-secrets.io/enable-rotation: "true"

spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: coreos-secret-store
    kind: SecretStore

  target:
    name: coreos-secrets
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: coreos
          app.kubernetes.io/part-of: coreos-platform
          app.kubernetes.io/managed-by: external-secrets
          security.coreos.io/encrypted: "true"
        annotations:
          kubernetes.io/description: Core platform secrets managed by External Secrets Operator
          reloader.stakater.com/match: "true"
          vault.security.coreos.io/rotation-period: "168h"
          audit.security.coreos.io/enabled: "true"

  data:
    # Backend secrets
    - secretKey: backend.SECRET_KEY
      remoteRef:
        key: coreos/backend/secret-key
        property: value
        version: AWSCURRENT

    - secretKey: backend.JWT_SECRET
      remoteRef:
        key: coreos/backend/jwt-secret
        property: value
        version: AWSCURRENT

    - secretKey: backend.DATABASE_URL
      remoteRef:
        key: coreos/backend/database-url
        property: value
        version: AWSCURRENT

    - secretKey: backend.REDIS_URL
      remoteRef:
        key: coreos/backend/redis-url
        property: value
        version: AWSCURRENT

    - secretKey: backend.OAUTH_CLIENT_ID
      remoteRef:
        key: coreos/backend/oauth-client-id
        property: value
        version: AWSCURRENT

    - secretKey: backend.OAUTH_CLIENT_SECRET
      remoteRef:
        key: coreos/backend/oauth-client-secret
        property: value
        version: AWSCURRENT

    - secretKey: backend.ENCRYPTION_KEY
      remoteRef:
        key: coreos/backend/encryption-key
        property: value
        version: AWSCURRENT

    # Frontend secrets
    - secretKey: frontend.VITE_AUTH_CLIENT_ID
      remoteRef:
        key: coreos/frontend/auth-client-id
        property: value
        version: AWSCURRENT

    - secretKey: frontend.VITE_AUTH_CLIENT_SECRET
      remoteRef:
        key: coreos/frontend/auth-client-secret
        property: value
        version: AWSCURRENT

    - secretKey: frontend.VITE_API_KEY
      remoteRef:
        key: coreos/frontend/api-key
        property: value
        version: AWSCURRENT

    # Monitoring secrets
    - secretKey: monitoring.GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: coreos/monitoring/grafana-admin-password
        property: value
        version: AWSCURRENT

    - secretKey: monitoring.PROMETHEUS_AUTH_PASSWORD
      remoteRef:
        key: coreos/monitoring/prometheus-auth-password
        property: value
        version: AWSCURRENT