apiVersion: external-secrets.io/v1beta1  # version: v1beta1
kind: SecretStore
metadata:
  name: coreos-secret-store
  namespace: coreos
  labels:
    app.kubernetes.io/name: coreos
    app.kubernetes.io/part-of: coreos-platform
    app.kubernetes.io/component: secret-store
    security.coreos.io/compliance: soc2-iso27001
    security.coreos.io/encryption: enabled
  annotations:
    secret-store.coreos.io/audit-logging: enabled
    secret-store.coreos.io/rotation-schedule: "168h"  # 7 days rotation schedule
    secret-store.coreos.io/last-rotation: "2024-01-01T00:00:00Z"  # Will be updated by operator
spec:
  # Provider configuration for both AWS and Azure
  provider:
    # AWS Secrets Manager configuration
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: coreos-sa  # References service account from base/serviceaccount.yaml
      retrySettings:
        maxRetries: 3
        retryInterval: "5s"
    
    # Azure Key Vault configuration
    azure:
      vaultUrl: https://coreos-kv.vault.azure.net
      authSecretRef:
        clientId:
          name: azure-secret-creds
          key: client-id
        clientSecret:
          name: azure-secret-creds
          key: client-secret
      identityId: system-assigned  # Using system-assigned managed identity
  
  # Global settings for the SecretStore
  refreshInterval: "1h"  # Refresh secrets every hour
  retrySettings:
    maxRetries: 5
    retryInterval: "30s"