# Kubernetes Secret resource for COREos platform
# Version: v1
# Managed by External Secrets Operator with AES-256-GCM encryption
apiVersion: v1
kind: Secret
metadata:
  name: coreos-secrets
  namespace: coreos
  labels:
    app.kubernetes.io/name: coreos
    app.kubernetes.io/part-of: coreos-platform
    app.kubernetes.io/managed-by: external-secrets
    security.coreos.io/encryption: aes256-gcm
  annotations:
    kubernetes.io/description: Core platform secrets managed by External Secrets Operator with AES-256-GCM encryption
    reloader.stakater.com/match: "true"
    secret.coreos.io/rotation-schedule: "168h"
    secret.coreos.io/last-rotated: "timestamp"
    secret.coreos.io/audit-log: "enabled"
type: Opaque
data:
  # Backend service secrets
  backend.SECRET_KEY: ${SECRET_KEY}
  backend.JWT_SECRET: ${JWT_SECRET}
  backend.JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  backend.DATABASE_URL: ${DATABASE_URL}
  backend.REDIS_URL: ${REDIS_URL}
  backend.OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
  backend.OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
  backend.ENCRYPTION_KEY: ${ENCRYPTION_KEY}
  backend.MFA_SECRET_KEY: ${MFA_SECRET_KEY}
  backend.API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}

  # Frontend application secrets
  frontend.VITE_AUTH_CLIENT_ID: ${VITE_AUTH_CLIENT_ID}
  frontend.VITE_AUTH_CLIENT_SECRET: ${VITE_AUTH_CLIENT_SECRET}
  frontend.VITE_API_KEY: ${VITE_API_KEY}
  frontend.VITE_ENCRYPTION_KEY: ${VITE_ENCRYPTION_KEY}

  # Monitoring stack secrets
  monitoring.GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
  monitoring.PROMETHEUS_AUTH_PASSWORD: ${PROMETHEUS_AUTH_PASSWORD}
  monitoring.ALERT_WEBHOOK_SECRET: ${ALERT_WEBHOOK_SECRET}

  # Cloud integration secrets
  integration.AWS_SECRET_KEY: ${AWS_SECRET_KEY}
  integration.AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
  integration.GCP_SERVICE_KEY: ${GCP_SERVICE_KEY}