apiVersion: v1
kind: ServiceAccount
metadata:
  name: coreos-service-account
  namespace: coreos
  labels:
    # Core application labels
    app.kubernetes.io/name: coreos-service-account
    app.kubernetes.io/part-of: coreos-platform
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/version: ${VERSION}
    app.kubernetes.io/environment: ${ENVIRONMENT}
    
    # Security labels
    security.coreos.io/audit: enabled

  annotations:
    # Cloud provider IAM integration
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/coreos-service-role
    azure.workload.identity/client-id: ${AZURE_CLIENT_ID}
    
    # Service mesh integration
    istio.io/service-account: "true"
    linkerd.io/inject: enabled
    
    # Security and audit configuration
    security.coreos.io/audit-level: high
    
    # Backup configuration
    backup.velero.io/include: "true"
    
    # Security controls
    auth.coreos.io/token-rotation: enabled
    
    # Monitoring
    monitoring.coreos.io/scrape: "true"