name: Web CI

on:
  push:
    paths:
      - 'src/web/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    paths:
      - 'src/web/**'
      - '.github/workflows/web-ci.yml'

permissions:
  contents: read
  actions: read
  checks: write

# Ensure only one workflow runs at a time per branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '18.x'
  WORKING_DIRECTORY: src/web

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: src/web/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.WORKING_DIRECTORY }}/node_modules
          key: npm-deps-${{ hashFiles('src/web/package-lock.json') }}
          restore-keys: |
            npm-deps-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Type check
        run: npm run typecheck

      - name: Lint check
        run: npm run lint
        
      - name: Run security audit
        run: npm run security:audit
        continue-on-error: true

      - name: Run tests with coverage
        run: npm run test:coverage
        env:
          CI: true
          JEST_JUNIT_OUTPUT_DIR: ./coverage/junit
          
      - name: Build application
        run: npm run build
        env:
          CI: true
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ env.WORKING_DIRECTORY }}/dist
          retention-days: 7
          if-no-files-found: error

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ${{ env.WORKING_DIRECTORY }}/coverage
          retention-days: 7
          if-no-files-found: error

      - name: Check bundle size
        run: npm run analyze
        continue-on-error: true